---
- name: update DirectAdmin custombuild
  command: "/usr/local/directadmin/custombuild/build update"
  when: "apache_version not in da_apache_version.stdout"

- name: build apache
  command: "/usr/local/directadmin/custombuild/build apache"
  when: "apache_version not in da_apache_version.stdout"

- name: recompile php
  command: "/usr/local/directadmin/custombuild/build php n"
  notify: restart apache
  when: "apache_version not in da_apache_version.stdout"
