---
- name: update DirectAdmin custombuild
  command: /usr/local/directadmin/custombuild/build update
  register: build_update

- name: build ioncube loader
  command: /usr/local/directadmin/custombuild/build ioncube
  register: build_ioncube
