---
- name: build update
  command: /usr/local/directadmin/custombuild/build update
  register: build_update

- name: build letsencrypt
  command: /usr/local/directadmin/custombuild/build letsencrypt
  register: build_letsencrypt
