---
- include: prerequisites.yml
- include: setup.yml

- include: php.yml
- include: ioncube_loader.yml
- include: mysql.yml
- include: apache.yml
- include: eximconf.yml
- include: spamassassin.yml
- include: easy_spam_fighter.yml
- include: letsencrypt.yml
- include: dkim.yml
- include: opcache.yml
