---
- include: prerequisites.yml
- include: setup.yml

- include: php.yml
  when: php|changed
- include: ioncube_loader.yml
  when: ioncube_loader|changed
- include: mysql.yml
  when: mysql|changed
- include: apache.yml
  when: apache|changed
- include: eximconf.yml
  when: eximconf|changed
- include: spamassassin.yml
  when: spamassassin|changed
- include: easy_spam_fighter.yml
  when: easu_spam_fighter|changed
- include: letsencrypt.yml
  when: letsencrypt|changed
- include: dkim.yml
  when: dkim|changed
- include: opcache.yml
  when: opcache|changed
