---
- include: prerequisites.yml
- include: setup.yml

- name: check which version of apache is defined in options.conf
  shell: "cat /usr/local/directadmin/custombuild/options.conf | awk -F= '/apache_ver/{print $2}'"
  register: da_apache_version
  changed_when: false
