---
- include: prerequisites.yml
- include: setup.yml

- name: check which version of apache is defined in options.conf
  shell: "cat /usr/local/directadmin/custombuild/options.conf | awk -F= '/apache_ver/{print $2}'"
  register: da_apache_version
  changed_when: false

- include: tasks/apache.yml

- name: check which version of php is defined in options.conf
  shell: "cat /usr/local/directadmin/custombuild/options.conf | awk -F= '/php1_rel/{print $2}'"
  register: da_php_version
  changed_when: false

- name: include apache.yml when version is changed
  include: tasks/apache.yml
  when: "apache_version not in da_php_version.stdout"
