---
# Ensure all variables are present to start with:
- name: verify all required variables are set
  fail:
    msg: "Variable: '{{ item }}' is not defined!"
  when: "{{ item }} is undefined or {{ item }} is none"
  with_items:
    - directadmin_license_id

# Ensure prerequisites are installed for supported OS
- include: packages.yml
