---
- name: obtain setup.sh script
  get_url:
    url: "{{ directadmin_setup_url }}"
    dest: "{{ directadmin_setup_path }}"

- name: ensure proper permissions on setup.sh
  file:
    path: "{{ directadmin_setup_path }}/setup.sh"
    mode: 0755

- name: "Set up custombuild version"
  copy:
    content: "2.0"
    dest: /root/.custombuild
    force: no
    mode: 644

- name: install directadmin
  command: /root/setup.sh {{ client_id }} {{ license_id }} {{ inventory_hostname }} {{ interface }}
