---
- name: check with version of php is running
  shell: "cat options.conf | awk -F= '/php1_rel/{print $2}'"
  register: php_version_current
  changed_when: "php_version not in php_version_current.stdout"

- include: php.yml
  when: php_version_current|changed
