---
- name: restart directadmin
  service:
    name: directadmin
    state: restarted

- name: restart apache
  service:
    name: httpd
    state: restarted

- name: restart exim
  service:
    name: exim
    state: restarted